# fly.toml file generated for post-to-screen on 2022-09-16T09:47:40+02:00

app = "post-to-screen"



[[services]]
    internal_port = 10555
    protocol = "tcp"

[[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

[[services.ports]]
    handlers = ["tls", "http"]
    port = "443"